# Generated by Django 3.0.3 on 2020-02-07 14:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_uuid', models.UUIDField()),
                ('ordered_at', models.DateTimeField()),
                ('cancelled_order', models.BooleanField(default=0)),
                ('finished_order', models.BooleanField()),
                ('status', models.IntegerField()),
                ('chef_name', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='KelnerBots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('bot_uuid', models.UUIDField()),
                ('bot_model', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='kelners/')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='MenuList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('menu_image', models.ImageField(upload_to='menu_images/')),
                ('menu_pid', models.UUIDField()),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='TableNodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id', models.IntegerField()),
                ('table_uuid', models.UUIDField()),
                ('is_occupied', models.BooleanField(default='False')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='UserReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=20)),
                ('reviewed_at', models.DateTimeField()),
                ('star', models.IntegerField()),
                ('review_desc', models.TextField(max_length=100)),
                ('most_liked_dish', models.CharField(max_length=20)),
                ('disliked_dish', models.CharField(max_length=25)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='RestaurantInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=30)),
                ('website', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=25)),
                ('long_lat', models.CharField(max_length=22, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('restaurant_image', models.ImageField(upload_to='restaurant/')),
                ('rating', models.IntegerField()),
                ('open_date', models.DateTimeField()),
                ('close_date', models.DateTimeField()),
                ('menu_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_list_menulist', to='main.MenuList')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='MenuElements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=30)),
                ('dish_image', models.ImageField(upload_to='dish/')),
                ('dish_ingredients', models.TextField(max_length=200)),
                ('dish_price', models.FloatField()),
                ('dish_quantity', models.IntegerField()),
                ('dish_measure', models.CharField(max_length=5)),
                ('dish_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_type_menulist', to='main.MenuList')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='KelnerOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_started', models.DateTimeField()),
                ('order_finished', models.DateTimeField()),
                ('kelner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kelners', to='main.KelnerBots')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='main.CustomerOrders')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.AddField(
            model_name='customerorders',
            name='dish_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_list_menuelements', to='main.MenuElements'),
        ),
        migrations.AddField(
            model_name='customerorders',
            name='ordered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_by_tablenodes', to='main.TableNodes'),
        ),
    ]
