# Generated by Django 3.0.3 on 2020-02-07 15:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menulist',
            name='menu_pid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
