# Generated by Django 3.0.3 on 2020-02-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200207_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='menulist',
            name='products',
            field=models.ManyToManyField(related_name='menu_elements', to='main.MenuElements'),
        ),
    ]
